IF OBJECT_ID(N'Tracker', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE Tracker
	IF COL_LENGTH('Tracker', 'UserId') IS NULL
	BEGIN
		ALTER TABLE Tracker
		ADD UserId NVARCHAR(450) NOT NULL
	END
END

IF COL_LENGTH('Tracker', 'UserId') IS NOT NULL
BEGIN
	ALTER TABLE Tracker
	ADD CONSTRAINT FK_Tracker_AspNetUsers_UserId
	FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id);
END